name: detect_change_path
on: [push]

jobs:
  detect_changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Helm Installation
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1
        id: install
      - uses: dorny/paths-filter@v2
        id: filter
        with:
            list-files: shell
            filters: |
              markdown:
                - added|modified: '!.github/**'
      - name: Print Markdown
        if: ${{ steps.filter.outputs.markdown == 'true' }}
        run: |
          charts=""
          for i in ${{ steps.filter.outputs.markdown_files }}
            do 
              charts+=" `echo $i  | awk -F / '{print $1} '`"
            done
          charts=`echo $charts| xargs -n1 | sort -u | xargs`
          echo $charts | xargs helm package