name: detect_change_path
on: [push]

jobs:
  detect_changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: dorny/paths-filter@v2
        id: filter
        with:
            list-files: shell
            filters: |
              markdown:
                - added|modified: '!.github/**'
      - name: Print Markdown
        if: ${{ steps.filter.outputs.markdown == 'true' }}
        run: |
          files=""
          for i in ${{ steps.filter.outputs.markdown_files }}
            do 
              var=`echo $i  | awk -F / '{print $1} '`
              files+=" $var"

            done
          echo $files